all: clear test1 test2 test3 test4 test5

clear:
	clear

test1: clear
	gcc -o test1 programA.c

test2: clear
	gcc -o test2 programB.c

test3: clear
	gcc -o test3 programC.c

test4: clear
	gcc -o test4 programD.c
	
test5: clear
	gcc -o test5 programE.c

clean:
	rm -rf a.out test1 test2 test3 test4 test5